version: '3.7'

services:

  db:
    image: mcs07/postgres-rdkit
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: rdkit_demo
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432